---
- name: create account
  user:
    name: '{{ username }}'
    groups: 'sudo'
    append: yes
    password: '{{ password }}'
    shell: '/bin/bash'
    home: '/home/{{ username }}'

- name: install nginx
  apt:
    name: nginx
    state: latest
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: copy html
  copy:
    src: './files/index.html'
    dest: '/var/www/html/index.html'

- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: wait for 30 seconds
  wait_for:
    timeout: 30

- name: stop nginx
  service:
    name: nginx
    state: stop
