---
- name: create account
  user:
    name: '{{ username }}'
    groups: 'sudo'
    append: yes
    password: '{{ password }}'
    shell: '/bin/bash'
    home: '/home/{{ username }}'

- name: install python3
  apt:
    name: python3
    state: present
    update_cache: true
    cache_valid_time: 3600
    force_apt_get: true

- name: copy script
  copy:
    src: './files/script.py'
    dest: '/home/{{ username }}/script.py'
    mode: '755'
    owner: '{{ username }}'
    group: 'sudo'

- name: start script each minute
  ansible.builtin.cron:
    name: 'run script every minuts'
    minute: '*/1'
    job: '/home/{{ username }}/script.py'